# MLProject/conda.yaml
name: my_ml_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow>=2.0
    - pandas
    - numpy
    - scikit-learn
    - tensorflow